export const skillsList = [
  { label: ".NET", value: ".NET"},
  { label: "account management", value: "account management"},
  { label: "Account representative", value: "Account representative"},
  { label: "accounting", value: "accounting"},
  { label: "accounts payable", value: "accounts payable"},
  { label: "Accounts receivable", value: "Accounts receivable"},
  { label: "acquisition", value: "acquisition"},
  { label: "Active listening", value: "Active listening"},
  { label: "Ad-hoc analysis", value: "Ad-hoc analysis"},
  { label: "Adaptability", value: "Adaptability"},
  { label: "administrative support", value: "administrative support"},
  { label: "admissions", value: "admissions"},
  { label: "Adobe", value: "Adobe"},
  { label: "Adobe After Effects", value: "Adobe After Effects"},
  { label: "Adobe Creative Cloud", value: "Adobe Creative Cloud"},
  { label: "Adobe Creative Suite", value: "Adobe Creative Suite"},
  { label: "Adobe Illustrator", value: "Adobe Illustrator"},
  { label: "Adobe InDesign", value: "Adobe InDesign"},
  { label: "Adobe Photoshop", value: "Adobe Photoshop"},
  { label: "advertising", value: "advertising"},
  { label: "affiliate", value: "affiliate"},
  { label: "Agency experience", value: "Agency experience"},
  { label: "agile", value: "agile"},
  { label: "AI", value: "AI"},
  { label: "algorithms", value: "algorithms"},
  { label: "alliances", value: "alliances"},
  { label: "analysis", value: "analysis"},
  { label: "analytical", value: "analytical"},
  { label: "analytical skills", value: "analytical skills"},
  { label: "analytics", value: "analytics"},
  { label: "analyze data", value: "analyze data"},
  { label: "analyzing data", value: "analyzing data"},
  { label: "android", value: "android"},
  { label: "AngularJS", value: "AngularJS"},
  { label: "Animation", value: "Animation"},
  { label: "annual budget", value: "annual budget"},
  { label: "API", value: "API"},
  { label: "APIs", value: "APIs"},
  { label: "Application-development", value: "Application-development"},
  { label: "Applications", value: "Applications"},
  { label: "architecture", value: "architecture"},
  { label: "Art", value: "Art"},
  { label: "assembly", value: "assembly"},
  { label: "asset management", value: "asset management"},
  { label: "Attention to detail", value: "Attention to detail"},
  { label: "audio", value: "audio"},
  { label: "audit", value: "audit"},
  { label: "auditing", value: "auditing"},
  { label: "AutoCAD", value: "AutoCAD"},
  { label: "automation", value: "automation"},
  { label: "aviation", value: "aviation"},
  { label: "AWS", value: "AWS"},
  { label: "Back End", value: "Back End"},
  { label: "banking", value: "banking"},
  { label: "Banner ads", value: "Banner ads"},
  { label: "benchmark", value: "benchmark"},
  { label: "BI", value: "BI"},
  { label: "big data", value: "big data"},
  { label: "billing", value: "billing"},
  { label: "biology", value: "biology"},
  { label: "brand", value: "brand"},
  { label: "Brand awareness", value: "Brand awareness"},
  { label: "Brand consistency", value: "Brand consistency"},
  { label: "Branded content", value: "Branded content"},
  { label: "branding", value: "branding"},
  { label: "broadcast", value: "broadcast"},
  { label: "Brochure design", value: "Brochure design"},
  { label: "budget", value: "budget"},
  { label: "budget management", value: "budget management"},
  { label: "Budgeting", value: "Budgeting"},
  { label: "build relationships", value: "build relationships"},
  { label: "Business acumen", value: "Business acumen"},
  { label: "business administration", value: "business administration"},
  { label: "business analysis", value: "business analysis"},
  { label: "business cases", value: "business cases"},
  { label: "business continuity", value: "business continuity"},
  { label: "business development", value: "business development"},
  { label: "business intelligence", value: "business intelligence"},
  { label: "business issues", value: "business issues"},
  { label: "business management", value: "business management"},
  { label: "business planning", value: "business planning"},
  { label: "business plans", value: "business plans"},
  { label: "business process", value: "business process"},
  { label: "business requirements", value: "business requirements"},
  { label: "business stakeholders", value: "business stakeholders"},
  { label: "business strategy", value: "business strategy"},
  { label: "Business support", value: "Business support"},
  { label: "business systems", value: "business systems"},
  { label: "Business volume", value: "Business volume"},
  { label: "C (programming language)", value: "C (programming language)"},
  { label: "C#", value: "C#"},
  { label: "C++", value: "C++"},
  { label: "call center", value: "call center"},
  { label: "Call center management", value: "Call center management"},
  { label: "Campaign", value: "Campaign"},
  { label: "Capital raising", value: "Capital raising"},
  { label: "case management", value: "case management"},
  { label: "cash flow", value: "cash flow"},
  { label: "certification", value: "certification"},
  { label: "CFA", value: "CFA"},
  { label: "change management", value: "change management"},
  { label: "chemicals", value: "chemicals"},
  { label: "chemistry", value: "chemistry"},
  { label: "circuits", value: "circuits"},
  { label: "Cisco", value: "Cisco"},
  { label: "Client accounts", value: "Client accounts"},
  { label: "Client communication", value: "Client communication"},
  { label: "Client needs", value: "Client needs"},
  { label: "Client outreach", value: "Client outreach"},
  { label: "client relationships", value: "client relationships"},
  { label: "client service", value: "client service"},
  { label: "cloud", value: "cloud"},
  { label: "Cloud computing", value: "Cloud computing"},
  { label: "Cloud networking", value: "Cloud networking"},
  { label: "CMS", value: "CMS"},
  { label: "co-op", value: "co-op"},
  { label: "coaching", value: "coaching"},
  { label: "coding", value: "coding"},
  { label: "Collateral", value: "Collateral"},
  { label: "Color", value: "Color"},
  { label: "Color theory", value: "Color theory"},
  { label: "commissioning", value: "commissioning"},
  { label: "Communication", value: "Communication"},
  { label: "Compatibility", value: "Compatibility"},
  { label: "Competitive analysis", value: "Competitive analysis"},
  { label: "complex projects", value: "complex projects"},
  { label: "compliance", value: "compliance"},
  { label: "Composition", value: "Composition"},
  { label: "computer applications", value: "computer applications"},
  { label: "computer science", value: "computer science"},
  { label: "computer software", value: "computer software"},
  { label: "Concept", value: "Concept"},
  { label: "Conceptualization", value: "Conceptualization"},
  { label: "Conflict resolution", value: "Conflict resolution"},
  { label: "construction", value: "construction"},
  { label: "consulting", value: "consulting"},
  { label: "consulting experience", value: "consulting experience"},
  { label: "consulting services", value: "consulting services"},
  { label: "consumers", value: "consumers"},
  { label: "content", value: "content"},
  { label: "Content management", value: "Content management"},
  { label: "Content marketing", value: "Content marketing"},
  { label: "continuous improvement", value: "continuous improvement"},
  { label: "contract management", value: "contract management"},
  { label: "contracts", value: "contracts"},
  { label: "controls", value: "controls"},
  { label: "conversion", value: "conversion"},
  { label: "Corporate finance", value: "Corporate finance"},
  { label: "correspondence", value: "correspondence"},
  { label: "Cost analysis", value: "Cost analysis"},
  { label: "cost effective", value: "cost effective"},
  { label: "cost reduction", value: "cost reduction"},
  { label: "Cost/benefit analysis", value: "Cost/benefit analysis"},
  { label: "counsel", value: "counsel"},
  { label: "counseling", value: "counseling"},
  { label: "CPA", value: "CPA"},
  { label: "CPG", value: "CPG"},
  { label: "CPR", value: "CPR"},
  { label: "Creative", value: "Creative"},
  { label: "CRM", value: "CRM"},
  { label: "cross-functional team", value: "cross-functional team"},
  { label: "CSS", value: "CSS"},
  { label: "Customer base", value: "Customer base"},
  { label: "Customer communication", value: "Customer communication"},
  { label: "Customer engagement", value: "Customer engagement"},
  { label: "customer experience", value: "customer experience"},
  { label: "customer facing", value: "customer facing"},
  { label: "Customer feedback", value: "Customer feedback"},
  { label: "Customer needs", value: "Customer needs"},
  { label: "Customer relations", value: "Customer relations"},
  { label: "Customer relationships", value: "Customer relationships"},
  { label: "customer requirements", value: "customer requirements"},
  { label: "Customer retention", value: "Customer retention"},
  { label: "Customer satisfaction", value: "Customer satisfaction"},
  { label: "customer service", value: "customer service"},
  { label: "Customer support", value: "Customer support"},
  { label: "customer-facing", value: "customer-facing"},
  { label: "Cybersecurity", value: "Cybersecurity"},
  { label: "D (programming language)", value: "D (programming language)"},
  { label: "daily operations", value: "daily operations"},
  { label: "Data", value: "Data"},
  { label: "data analysis", value: "data analysis"},
  { label: "data center", value: "data center"},
  { label: "data collection", value: "data collection"},
  { label: "data entry", value: "data entry"},
  { label: "Data interpretation", value: "Data interpretation"},
  { label: "data management", value: "data management"},
  { label: "data quality", value: "data quality"},
  { label: "Data recovery", value: "Data recovery"},
  { label: "Data-driven", value: "Data-driven"},
  { label: "database", value: "database"},
  { label: "Database management", value: "Database management"},
  { label: "Datacenter", value: "Datacenter"},
  { label: "datasets", value: "datasets"},
  { label: "deposits", value: "deposits"},
  { label: "design", value: "design"},
  { label: "Desktop support", value: "Desktop support"},
  { label: "Detail-oriented", value: "Detail-oriented"},
  { label: "development activities", value: "development activities"},
  { label: "Digital ads", value: "Digital ads"},
  { label: "Digital advertising", value: "Digital advertising"},
  { label: "Digital campaign", value: "Digital campaign"},
  { label: "Digital design", value: "Digital design"},
  { label: "digital marketing", value: "digital marketing"},
  { label: "digital media", value: "digital media"},
  { label: "Disaster recovery", value: "Disaster recovery"},
  { label: "Dispute resolution", value: "Dispute resolution"},
  { label: "distribution", value: "distribution"},
  { label: "DNS", value: "DNS"},
  { label: "documentation", value: "documentation"},
  { label: "documenting", value: "documenting"},
  { label: "drafting", value: "drafting"},
  { label: "drawings", value: "drawings"},
  { label: "Dreamweaver", value: "Dreamweaver"},
  { label: "due diligence", value: "due diligence"},
  { label: "dynamic environment", value: "dynamic environment"},
  { label: "e-commerce", value: "e-commerce"},
  { label: "economics", value: "economics"},
  { label: "editing", value: "editing"},
  { label: "editorial", value: "editorial"},
  { label: "electrical", value: "electrical"},
  { label: "electrical engineering", value: "electrical engineering"},
  { label: "electronics", value: "electronics"},
  { label: "Email marketing", value: "Email marketing"},
  { label: "Empathy", value: "Empathy"},
  { label: "employee engagement", value: "employee engagement"},
  { label: "employee relations", value: "employee relations"},
  { label: "end user", value: "end user"},
  { label: "engagement", value: "engagement"},
  { label: "engineering", value: "engineering"},
  { label: "ERP", value: "ERP"},
  { label: "ETL", value: "ETL"},
  { label: "event planning", value: "event planning"},
  { label: "expenses", value: "expenses"},
  { label: "experimental", value: "experimental"},
  { label: "experiments", value: "experiments"},
  { label: "external partners", value: "external partners"},
  { label: "fabrication", value: "fabrication"},
  { label: "Facebook", value: "Facebook"},
  { label: "fashion", value: "fashion"},
  { label: "FDA", value: "FDA"},
  { label: "field sales", value: "field sales"},
  { label: "filing", value: "filing"},
  { label: "finance", value: "finance"},
  { label: "financial analysis", value: "financial analysis"},
  { label: "Financial data", value: "Financial data"},
  { label: "Financial forecasting", value: "Financial forecasting"},
  { label: "financial management", value: "financial management"},
  { label: "Financial modeling", value: "Financial modeling"},
  { label: "financial performance", value: "financial performance"},
  { label: "Financial policy", value: "Financial policy"},
  { label: "financial reporting", value: "financial reporting"},
  { label: "financial reports", value: "financial reports"},
  { label: "financial services", value: "financial services"},
  { label: "financial statements", value: "financial statements"},
  { label: "financing", value: "financing"},
  { label: "Firewall", value: "Firewall"},
  { label: "fitness", value: "fitness"},
  { label: "Flex", value: "Flex"},
  { label: "forecasting", value: "forecasting"},
  { label: "forecasts", value: "forecasts"},
  { label: "Forensic accounting", value: "Forensic accounting"},
  { label: "frameworks", value: "frameworks"},
  { label: "front-end", value: "front-end"},
  { label: "fulfillment", value: "fulfillment"},
  { label: "Full Stack", value: "Full Stack"},
  { label: "fundraising", value: "fundraising"},
  { label: "GAAP", value: "GAAP"},
  { label: "general ledger", value: "general ledger"},
  { label: "German", value: "German"},
  { label: "GIS", value: "GIS"},
  { label: "Git", value: "Git"},
  { label: "Google Analytics", value: "Google Analytics"},
  { label: "governance", value: "governance"},
  { label: "graphic design", value: "graphic design"},
  { label: "Graphics", value: "Graphics"},
  { label: "hardware", value: "hardware"},
  { label: "health", value: "health"},
  { label: "healthcare", value: "healthcare"},
  { label: "help desk", value: "help desk"},
  { label: "higher education", value: "higher education"},
  { label: "hospital", value: "hospital"},
  { label: "hospitality", value: "hospitality"},
  { label: "hotel", value: "hotel"},
  { label: "HRIS", value: "HRIS"},
  { label: "HTML", value: "HTML"},
  { label: "human resource", value: "human resource"},
  { label: "I-DEAS", value: "I-DEAS"},
  { label: "IaaS", value: "IaaS"},
  { label: "IBM", value: "IBM"},
  { label: "Identified trends", value: "Identified trends"},
  { label: "Illustration", value: "Illustration"},
  { label: "Imaging", value: "Imaging"},
  { label: "immigration", value: "immigration"},
  { label: "in-store", value: "in-store"},
  { label: "InDesign", value: "InDesign"},
  { label: "industry experience", value: "industry experience"},
  { label: "industry trends", value: "industry trends"},
  { label: "information management", value: "information management"},
  { label: "information security", value: "information security"},
  { label: "information system", value: "information system"},
  { label: "information technology", value: "information technology"},
  { label: "installation", value: "installation"},
  { label: "instructional design", value: "instructional design"},
  { label: "instrumentation", value: "instrumentation"},
  { label: "internal audit", value: "internal audit"},
  { label: "internal communications", value: "internal communications"},
  { label: "internal controls", value: "internal controls"},
  { label: "internal customers", value: "internal customers"},
  { label: "internal stakeholders", value: "internal stakeholders"},
  { label: "international", value: "international"},
  { label: "internship", value: "internship"},
  { label: "Interpersonal communication", value: "Interpersonal communication"},
  { label: "Interpersonal skills", value: "Interpersonal skills"},
  { label: "intranet", value: "intranet"},
  { label: "inventory", value: "inventory"},
  { label: "inventory management", value: "inventory management"},
  { label: "investigate", value: "investigate"},
  { label: "investigations", value: "investigations"},
  { label: "Investment management", value: "Investment management"},
  { label: "Investor relations", value: "Investor relations"},
  { label: "invoices", value: "invoices"},
  { label: "invoicing", value: "invoicing"},
  { label: "iOS", value: "iOS"},
  { label: "iPhone", value: "iPhone"},
  { label: "ISO", value: "ISO"},
  { label: "IT infrastructure", value: "IT infrastructure"},
  { label: "ITIL", value: "ITIL"},
  { label: "Java", value: "Java"},
  { label: "Javascript", value: "Javascript"},
  { label: "JIRA", value: "JIRA"},
  { label: "journal entries", value: "journal entries"},
  { label: "journalism", value: "journalism"},
  { label: "JQuery", value: "JQuery"},
  { label: "Key accounts", value: "Key accounts"},
  { label: "key performance indicators", value: "key performance indicators"},
  { label: "Keyword research", value: "Keyword research"},
  { label: "Knowledgebase", value: "Knowledgebase"},
  { label: "KPI", value: "KPI"},
  { label: "LAN", value: "LAN"},
  { label: "law enforcement", value: "law enforcement"},
  { label: "Layout", value: "Layout"},
  { label: "leadership development", value: "leadership development"},
  { label: "lean", value: "lean"},
  { label: "legal", value: "legal"},
  { label: "legislation", value: "legislation"},
  { label: "licensing", value: "licensing"},
  { label: "life cycle", value: "life cycle"},
  { label: "lighting", value: "lighting"},
  { label: "Linux", value: "Linux"},
  { label: "litigation", value: "litigation"},
  { label: "Local areas network", value: "Local areas network"},
  { label: "logistics", value: "logistics"},
  { label: "Logo design", value: "Logo design"},
  { label: "Loss prevention", value: "Loss prevention"},
  { label: "Loyalty", value: "Loyalty"},
  { label: "machine learning", value: "machine learning"},
  { label: "manage projects", value: "manage projects"},
  { label: "Managed", value: "Managed"},
  { label: "management consulting", value: "management consulting"},
  { label: "management experience", value: "management experience"},
  { label: "Market insights", value: "Market insights"},
  { label: "market research", value: "market research"},
  { label: "marketing", value: "marketing"},
  { label: "Marketing analytics", value: "Marketing analytics"},
  { label: "Marketing campaign", value: "Marketing campaign"},
  { label: "Marketing manager", value: "Marketing manager"},
  { label: "marketing materials", value: "marketing materials"},
  { label: "marketing plans", value: "marketing plans"},
  { label: "marketing programs", value: "marketing programs"},
  { label: "Marketing strategies", value: "Marketing strategies"},
  { label: "marketing strategy", value: "marketing strategy"},
  { label: "mathematics", value: "mathematics"},
  { label: "MATLAB", value: "MATLAB"},
  { label: "matrix", value: "matrix"},
  { label: "mechanical engineering", value: "mechanical engineering"},
  { label: "Media", value: "Media"},
  { label: "Media campaign", value: "Media campaign"},
  { label: "media relations", value: "media relations"},
  { label: "medical device", value: "medical device"},
  { label: "merchandising", value: "merchandising"},
  { label: "metrics", value: "metrics"},
  { label: "Microsoft Office", value: "Microsoft Office"},
  { label: "Microsoft Office Suite", value: "Microsoft Office Suite"},
  { label: "Microsoft Word", value: "Microsoft Word"},
  { label: "migration", value: "migration"},
  { label: "mining", value: "mining"},
  { label: "MIS", value: "MIS"},
  { label: "mobile", value: "mobile"},
  { label: "Model View Controller", value: "Model View Controller"},
  { label: "modeling", value: "modeling"},
  { label: "mortgage", value: "mortgage"},
  { label: "MS Excel", value: "MS Excel"},
  { label: "MS Office", value: "MS Office"},
  { label: "MS Project", value: "MS Project"},
  { label: "MySQL", value: "MySQL"},
  { label: "negotiation", value: "negotiation"},
  { label: "Network", value: "Network"},
  { label: "Network administration", value: "Network administration"},
  { label: "Network engineering", value: "Network engineering"},
  { label: "networking", value: "networking"},
  { label: "Newsletter design", value: "Newsletter design"},
  { label: "Node.js", value: "Node.js"},
  { label: "non-profit", value: "non-profit"},
  { label: "nursing", value: "nursing"},
  { label: "office software", value: "office software"},
  { label: "on-boarding", value: "on-boarding"},
  { label: "on-call", value: "on-call"},
  { label: "Open-minded", value: "Open-minded"},
  { label: "operating systems", value: "operating systems"},
  { label: "operational excellence", value: "operational excellence"},
  { label: "operations", value: "operations"},
  { label: "operations management", value: "operations management"},
  { label: "oracle", value: "oracle"},
  { label: "Oral communication", value: "Oral communication"},
  { label: "Order fulfillment", value: "Order fulfillment"},
  { label: "Order processing", value: "Order processing"},
  { label: "ordering", value: "ordering"},
  { label: "Organized", value: "Organized"},
  { label: "OS", value: "OS"},
  { label: "outreach", value: "outreach"},
  { label: "outsourcing", value: "outsourcing"},
  { label: "P&L", value: "P&L"},
  { label: "partnership", value: "partnership"},
  { label: "Patience", value: "Patience"},
  { label: "payments", value: "payments"},
  { label: "payroll", value: "payroll"},
  { label: "PeopleSoft", value: "PeopleSoft"},
  { label: "performance improvement", value: "performance improvement"},
  { label: "performance metrics", value: "performance metrics"},
  { label: "pharmaceutical", value: "pharmaceutical"},
  { label: "pharmacy", value: "pharmacy"},
  { label: "phone calls", value: "phone calls"},
  { label: "photography", value: "photography"},
  { label: "Photoshop", value: "Photoshop"},
  { label: "PHP", value: "PHP"},
  { label: "physical security", value: "physical security"},
  { label: "physics", value: "physics"},
  { label: "PMP", value: "PMP"},
  { label: "policies", value: "policies"},
  { label: "Portfolio", value: "Portfolio"},
  { label: "portfolio management", value: "portfolio management"},
  { label: "Positioned", value: "Positioned"},
  { label: "positioning", value: "positioning"},
  { label: "PR", value: "PR"},
  { label: "presentation", value: "presentation"},
  { label: "Presentation skills", value: "Presentation skills"},
  { label: "presentations", value: "presentations"},
  { label: "Print design", value: "Print design"},
  { label: "Problem-solving", value: "Problem-solving"},
  { label: "process development", value: "process development"},
  { label: "process improvement", value: "process improvement"},
  { label: "Process simplification", value: "Process simplification"},
  { label: "Process standardization", value: "Process standardization"},
  { label: "procurement", value: "procurement"},
  { label: "product design", value: "product design"},
  { label: "product development", value: "product development"},
  { label: "product knowledge", value: "product knowledge"},
  { label: "Product launch", value: "Product launch"},
  { label: "product line", value: "product line"},
  { label: "product management", value: "product management"},
  { label: "product marketing", value: "product marketing"},
  { label: "Product positioning", value: "Product positioning"},
  { label: "product quality", value: "product quality"},
  { label: "Production", value: "Production"},
  { label: "program development", value: "program development"},
  { label: "programming", value: "programming"},
  { label: "project delivery", value: "project delivery"},
  { label: "project management", value: "project management"},
  { label: "project management skills", value: "project management skills"},
  { label: "project plan", value: "project plan"},
  { label: "project planning", value: "project planning"},
  { label: "proposal", value: "proposal"},
  { label: "prospecting", value: "prospecting"},
  { label: "protocols", value: "protocols"},
  { label: "prototype", value: "prototype"},
  { label: "psychology", value: "psychology"},
  { label: "public health", value: "public health"},
  { label: "public policy", value: "public policy"},
  { label: "public relations", value: "public relations"},
  { label: "Public relations", value: "Public relations"},
  { label: "publications", value: "publications"},
  { label: "publishing", value: "publishing"},
  { label: "purchase orders", value: "purchase orders"},
  { label: "purchasing", value: "purchasing"},
  { label: "Python", value: "Python"},
  { label: "QA", value: "QA"},
  { label: "Qualitative analysis", value: "Qualitative analysis"},
  { label: "quality assurance", value: "quality assurance"},
  { label: "quality control", value: "quality control"},
  { label: "quality management", value: "quality management"},
  { label: "quality standards", value: "quality standards"},
  { label: "Quantitative analysis", value: "Quantitative analysis"},
  { label: "R (programming language)", value: "R (programming language)"},
  { label: "raw materials", value: "raw materials"},
  { label: "real estate", value: "real estate"},
  { label: "real-time", value: "real-time"},
  { label: "reconcile", value: "reconcile"},
  { label: "Reconciled", value: "Reconciled"},
  { label: "reconciliation", value: "reconciliation"},
  { label: "Records management", value: "Records management"},
  { label: "recruit", value: "recruit"},
  { label: "recruiting", value: "recruiting"},
  { label: "recruitment", value: "recruitment"},
  { label: "regulations", value: "regulations"},
  { label: "regulatory", value: "regulatory"},
  { label: "regulatory compliance", value: "regulatory compliance"},
  { label: "regulatory requirements", value: "regulatory requirements"},
  { label: "relationship building", value: "relationship building"},
  { label: "relationship management", value: "relationship management"},
  { label: "Remote access", value: "Remote access"},
  { label: "Remote operations", value: "Remote operations"},
  { label: "Remote work", value: "Remote work"},
  { label: "repairs", value: "repairs"},
  { label: "reporting", value: "reporting"},
  { label: "Requirements analysis", value: "Requirements analysis"},
  { label: "research", value: "research"},
  { label: "research projects", value: "research projects"},
  { label: "Research skills", value: "Research skills"},
  { label: "researching", value: "researching"},
  { label: "resource management", value: "resource management"},
  { label: "Responsive", value: "Responsive"},
  { label: "retail", value: "retail"},
  { label: "retention", value: "retention"},
  { label: "revenue growth", value: "revenue growth"},
  { label: "RFP", value: "RFP"},
  { label: "Risk analysis", value: "Risk analysis"},
  { label: "risk assessment", value: "risk assessment"},
  { label: "risk management", value: "risk management"},
  { label: "root cause", value: "root cause"},
  { label: "routing", value: "routing"},
  { label: "SaaS", value: "SaaS"},
  { label: "safety", value: "safety"},
  { label: "sales", value: "sales"},
  { label: "Sales administration", value: "Sales administration"},
  { label: "Sales benchmarks", value: "Sales benchmarks"},
  { label: "sales experience", value: "sales experience"},
  { label: "sales goals", value: "sales goals"},
  { label: "Sales growth", value: "Sales growth"},
  { label: "sales management", value: "sales management"},
  { label: "sales operations", value: "sales operations"},
  { label: "Sales training", value: "Sales training"},
  { label: "SalesForce", value: "SalesForce"},
  { label: "SAP", value: "SAP"},
  { label: "SAS", value: "SAS"},
  { label: "scheduling", value: "scheduling"},
  { label: "SCI", value: "SCI"},
  { label: "scripting", value: "scripting"},
  { label: "scrum", value: "scrum"},
  { label: "SDLC", value: "SDLC"},
  { label: "Security", value: "Security"},
  { label: "security clearance", value: "security clearance"},
  { label: "segmentation", value: "segmentation"},
  { label: "SEO", value: "SEO"},
  { label: "Server", value: "Server"},
  { label: "Server maintenance", value: "Server maintenance"},
  { label: "service delivery", value: "service delivery"},
  { label: "SharePoint", value: "SharePoint"},
  { label: "six sigma", value: "six sigma"},
  { label: "Sketch", value: "Sketch"},
  { label: "small business", value: "small business"},
  { label: "social media", value: "social media"},
  { label: "software development", value: "software development"},
  { label: "software development life cycle", value: "software development life cycle"},
  { label: "software engineering", value: "software engineering"},
  { label: "SolidWorks", value: "SolidWorks"},
  { label: "SOPs", value: "SOPs"},
  { label: "Sourced", value: "Sourced"},
  { label: "sourcing", value: "sourcing"},
  { label: "specifications", value: "specifications"},
  { label: "spelling", value: "spelling"},
  { label: "sports", value: "sports"},
  { label: "spreadsheets", value: "spreadsheets"},
  { label: "SQL", value: "SQL"},
  { label: "SQL Server", value: "SQL Server"},
  { label: "staffing", value: "staffing"},
  { label: "stakeholder management", value: "stakeholder management"},
  { label: "standard operating procedures", value: "standard operating procedures"},
  { label: "standardization", value: "standardization"},
  { label: "start-up", value: "start-up"},
  { label: "statistical analysis", value: "statistical analysis"},
  { label: "statistics", value: "statistics"},
  { label: "status reports", value: "status reports"},
  { label: "Strategic business goals", value: "Strategic business goals"},
  { label: "strategic direction", value: "strategic direction"},
  { label: "strategic initiatives", value: "strategic initiatives"},
  { label: "Strategic marketing", value: "Strategic marketing"},
  { label: "Strategic oversight", value: "Strategic oversight"},
  { label: "strategic planning", value: "strategic planning"},
  { label: "strategic plans", value: "strategic plans"},
  { label: "strategy", value: "strategy"},
  { label: "strong analytical skills", value: "strong analytical skills"},
  { label: "Structured Query Language (SQL)", value: "Structured Query Language (SQL)"},
  { label: "supervising", value: "supervising"},
  { label: "supervisory experience", value: "supervisory experience"},
  { label: "supply chain", value: "supply chain"},
  { label: "supply chain management", value: "supply chain management"},
  { label: "Support", value: "Support"},
  { label: "support services", value: "support services"},
  { label: "Systems acquisition", value: "Systems acquisition"},
  { label: "Systems configuration", value: "Systems configuration"},
  { label: "Tableau", value: "Tableau"},
  { label: "tablets", value: "tablets"},
  { label: "talent acquisition", value: "talent acquisition"},
  { label: "talent management", value: "talent management"},
  { label: "tax", value: "tax"},
  { label: "teaching", value: "teaching"},
  { label: "technical", value: "technical"},
  { label: "technical issues", value: "technical issues"},
  { label: "technical knowledge", value: "technical knowledge"},
  { label: "technical skills", value: "technical skills"},
  { label: "technical support", value: "technical support"},
  { label: "Technology", value: "Technology"},
  { label: "telecom", value: "telecom"},
  { label: "Telemarketing", value: "Telemarketing"},
  { label: "test cases", value: "test cases"},
  { label: "test plans", value: "test plans"},
  { label: "testing", value: "testing"},
  { label: "therapeutic", value: "therapeutic"},
  { label: "trade shows", value: "trade shows"},
  { label: "training", value: "training"},
  { label: "transactions", value: "transactions"},
  { label: "transport", value: "transport"},
  { label: "transportation", value: "transportation"},
  { label: "travel", value: "travel"},
  { label: "travel arrangements", value: "travel arrangements"},
  { label: "troubleshooting", value: "troubleshooting"},
  { label: "Trust accounting", value: "Trust accounting"},
  { label: "TV", value: "TV"},
  { label: "Twitter", value: "Twitter"},
  { label: "Typography", value: "Typography"},
  { label: "UI", value: "UI"},
  { label: "underwriting", value: "underwriting"},
  { label: "Unix", value: "Unix"},
  { label: "usability", value: "usability"},
  { label: "User engagement", value: "User engagement"},
  { label: "user experience", value: "user experience"},
  { label: "User Interface Design", value: "User Interface Design"},
  { label: "UX", value: "UX"},
  { label: "valid drivers license", value: "valid drivers license"},
  { label: "value proposition", value: "value proposition"},
  { label: "variances", value: "variances"},
  { label: "vendor management", value: "vendor management"},
  { label: "Vendor management", value: "Vendor management"},
  { label: "Vendor relationships", value: "Vendor relationships"},
  { label: "vendors", value: "vendors"},
  { label: "Verbal communication", value: "Verbal communication"},
  { label: "video", value: "video"},
  { label: "Visual", value: "Visual"},
  { label: "VMware", value: "VMware"},
  { label: "warehouse", value: "warehouse"},
  { label: "Web design", value: "Web design"},
  { label: "Web Development", value: "Web Development"},
  { label: "web services", value: "web services"},
  { label: "Web strategy", value: "Web strategy"},
  { label: "windows", value: "windows"},
  { label: "Wireless", value: "Wireless"},
  { label: "Wireless networking", value: "Wireless networking"},
  { label: "workflows", value: "workflows"},
  { label: "writing", value: "writing"},
  { label: "Written communication", value: "Written communication"}
];